# Generated by Django 4.1.7 on 2023-02-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('courseCode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Masomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=30)),
                ('moduleCode', models.CharField(max_length=30)),
                ('moduleTeacher', models.CharField(max_length=30)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionsection', models.CharField(choices=[('YES', 'YES'), ('NO', ' NO')], default='YES', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicNumber', models.IntegerField()),
                ('topicName', models.CharField(max_length=30)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.masomo')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionLevel', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Normal', max_length=30)),
                ('questionText', models.TextField()),
                ('questiontype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questiontype')),
                ('somo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.masomo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.topic')),
            ],
        ),
    ]
