# Generated by Django 4.1.7 on 2023-02-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionLevel', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Normal', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='questionLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionlevel'),
        ),
    ]
