# Generated by Django 4.1.7 on 2023-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0002_questionlevel_alter_question_questionlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlevel',
            name='questionLevel',
            field=models.CharField(max_length=30),
        ),
    ]
