# Generated by Django 4.1.7 on 2023-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0003_alter_questionlevel_questionlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionLevel',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questiontype',
            field=models.CharField(choices=[('multichoice Questions', 'multichoice Questions'), ('short answers Questions', 'short answers Questions'), ('long answers Questions', 'long answers Questions')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='questionsection',
            name='questionsection',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', ' NO')], max_length=10, null=True),
        ),
    ]
