# Generated by Django 4.1.7 on 2023-05-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0004_alter_questionlongterm_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionType',
        ),
        migrations.RemoveField(
            model_name='question',
            name='somo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.DeleteModel(
            name='QCategory',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
