# Generated by Django 4.1.7 on 2023-03-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0004_alter_question_questionlevel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionLevel',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.RemoveField(
            model_name='masomo',
            name='moduleTeacher',
        ),
    ]
