# Generated by Django 2.2 on 2023-06-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0006_auto_20230621_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='option4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
