# Generated by Django 2.2 on 2023-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0007_auto_20230621_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlongterm',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionshortterm',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
