# Generated by Django 2.2 on 2023-05-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0002_auto_20230523_1757'),
        ('mtihani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtihani',
            name='deptname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.Department'),
        ),
    ]
