# Generated by Django 4.1.7 on 2023-05-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0020_mtihani_examtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtihaniTaarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(blank=True, max_length=100, null=True)),
                ('semeter', models.CharField(max_length=20)),
            ],
        ),
    ]
